// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {highlighting} from "./highlight"
export const parser = LRParser.deserialize({
  version: 14,
  states: "$nQVQPOOObQQO'#C^OOQO'#Cl'#ClOjQPO'#CuOxQPO'#CdOOQO'#Ce'#CeOOQO'#Ck'#CkOOQO'#Cf'#CfQVQPOOO}QPO,58xO!SQPO,58{OOQO,59a,59aO!XQPO,59OOOQO-E6d-E6dO!^QSO1G.dO!cQPO1G.gOOQO1G.j1G.jO!hQQO'#CpOOQO'#C`'#C`O!pQPO7+$OOOQO'#Cg'#CgO!uQPO'#CcO!}QPO7+$RO!^QSO,59[OOQO<<Gj<<GjOOQO-E6e-E6eOOQO<<Gm<<GmOOQO1G.v1G.v",
  stateData: "#V~O^OS~ObPOgROhSO~ORXOUYO~OgRO[iXbiXhiX~OgRO~Oc^O~Oc_O~Oh`O~OeaO~OgdO~OfgOadX~OahO~OgdOaVX~OajO~Og^~",
  goto: "!kjPPkPokPruuy!PPPP!VuPPP!ZPPPP!aTQOWRc^Rf_TUOWQWOR]WQe_RieTVOWQb^RkgSTOWQZRR[S",
  nodeNames: "⚠ Text RefEntity Global Grams RefSyntactic Offset Nominal Error Filler",
  maxTerm: 25,
  propSources: [highlighting],
  skippedNodes: [0],
  repeatNodeCount: 2,
  tokenData: ".]~R!WOX$kXZ%]Z^&Q^p$kpq%]qr'yr|$k|}(O}!O(l!O!Q$k!Q!R)o!R![*o![!b$k!b!c+q!c!d+|!d!e)o!e!f+|!f!g+|!g!h)o!h!i+|!i!p)o!p!q+|!q!r)o!r!s+|!s!t)o!t!u+|!u!v+|!v!w+|!w!z)o!z!{+|!{!})o!}#T$k#T#o)o#p#q.R#q#r.W#r#y$k#y#z&Q#z$f$k$f$g&Q$g#BY$k#BY#BZ&Q#BZ$IS$k$IS$I_&Q$I_$I|$k$I|$JO&Q$JO$JT$k$JT$JU&Q$JU$KV$k$KV$KW&Q$KW&FU$k&FU&FV&Q&FV;'S$k;'S;=`%V<%lO$kP$pVgPOX$kZp$kr!b$k!c#o$k#r;'S$k;'S;=`%V<%lO$kP%YP;=`<%l$k~%bY^~X^%]pq%]#y#z%]$f$g%]#BY#BZ%]$IS$I_%]$I|$JO%]$JT$JU%]$KV$KW%]&FU&FV%]~&XjgP^~OX$kXZ%]Z^&Q^p$kpq%]r!b$k!c#o$k#r#y$k#y#z&Q#z$f$k$f$g&Q$g#BY$k#BY#BZ&Q#BZ$IS$k$IS$I_&Q$I_$I|$k$I|$JO&Q$JO$JT$k$JT$JU&Q$JU$KV$k$KV$KW&Q$KW&FU$k&FU&FV&Q&FV;'S$k;'S;=`%V<%lO$k~(OOh~R(VVfQgPOX$kZp$kr!b$k!c#o$k#r;'S$k;'S;=`%V<%lO$kV(s^eSgPOX$kZp$kr}$k}!O)o!O!Q$k!Q!R)o!R![*o![!b$k!c!})o!}#T$k#T#o)o#r;'S$k;'S;=`%V<%lO$kT)v]eSgPOX$kZp$kr}$k}!O)o!O!Q$k!Q![)o![!b$k!c!})o!}#T$k#T#o)o#r;'S$k;'S;=`%V<%lO$kV*x]UQeSgPOX$kZp$kr}$k}!O)o!O!Q$k!Q![*o![!b$k!c!})o!}#T$k#T#o)o#r;'S$k;'S;=`%V<%lO$k~+tP#o#p+w~+|Ob~V,T^eSgPOX$kZp$kr}$k}!O)o!O!Q$k!Q!R)o!R![-P![!b$k!c!})o!}#T$k#T#o)o#r;'S$k;'S;=`%V<%lO$kV-Y]RQeSgPOX$kZp$kr}$k}!O)o!O!Q$k!Q![-P![!b$k!c!})o!}#T$k#T#o)o#r;'S$k;'S;=`%V<%lO$k~.WOc~~.]Oa~",
  tokenizers: [0, 1, 2],
  topRules: {"Text":[0,1]},
  tokenPrec: 96
})
