// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Text = 1,
  RefEntity = 2,
  Global = 3,
  Gram = 4,
  RefSyntactic = 5,
  Offset = 6,
  Nominal = 7,
  Word = 8
