# ======== Multi-stage base ==========
FROM node:22-bookworm-slim AS node-base
RUN apt-get update -qq && \
    apt-get upgrade -y && \
    rm -rf /var/lib/apt/lists/*

# ========= Server =======
FROM node-base AS product-server
ARG BUILD_TYPE=development

ENV NODE_ENV=development

WORKDIR /home
RUN npm install -g vite

COPY ./ ./
COPY ./env/.env.$BUILD_TYPE ./
RUN rm -rf ./env

RUN npm install
