# ======== Multi-stage base ==========
FROM node:24-bookworm-slim AS node-base
RUN apt-get update -qq && \
    apt-get upgrade -y && \
    rm -rf /var/lib/apt/lists/*
RUN corepack enable

# ========= Dev server =======
FROM node-base AS product-server
ARG BUILD_TYPE=development

ENV NODE_ENV=development

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml .npmrc ./
COPY rsconcept/domain/package.json rsconcept/domain/
COPY rsconcept/frontend/package.json rsconcept/frontend/
RUN pnpm install --filter frontend...

COPY rsconcept/domain rsconcept/domain
COPY rsconcept/frontend rsconcept/frontend
COPY rsconcept/frontend/env/.env.$BUILD_TYPE rsconcept/frontend/.env
RUN rm -rf rsconcept/frontend/env

RUN pnpm --filter @rsconcept/domain run build

WORKDIR /app/rsconcept/frontend
