// This file was generated by lezer-generator. You probably shouldn't edit it.
export const Expression = 1,
  Local = 2,
  Literal = 4,
  Global = 5,
  Radical = 6,
  Filter = 19,
  ComplexIndex = 20,
  PrefixD = 25,
  PrefixI = 26,
  PrefixR = 28,
  Function = 30,
  TextFunction = 31,
  Predicate = 44;
