# Global options:

[mypy]
warn_return_any = True
warn_unused_configs = True

plugins = 
  mypy_django_plugin.main

# Per-module options:
[mypy.plugins.django-stubs]
django_settings_module = "project.settings"

[mypy-cctext.*]
ignore_missing_imports = True

[mypy-apps.users.views]
disable_error_code = import-untyped

[mypy-apps.users.tests.t_views]
disable_error_code = import-untyped
