'''
Django settings for project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
'''

import logging
import os
import sys
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured


def _get_secret(key: str, default):
    value = os.environ.get(key, default)
    if os.path.isfile(value):
        with open(value, mode='r', encoding='utf-8') as f:
            return f.read()
    return value


def _get_bool(key: str, default: bool) -> bool:
    return os.environ.get(key, default) in _TRUE_VARIANTS


def _get_list(key: str, default: str) -> list[str]:
    return [value for value in os.environ.get(key, default).split(';') if value]


_TRUE_VARIANTS = [True, 'True', '1']
_MANAGEMENT_COMMAND = sys.argv[1].lower() if len(sys.argv) > 1 else ''
_SAFE_MANAGEMENT_COMMANDS = {
    'check',
    'test',
    'makemigrations',
    'migrate',
    'showmigrations',
    'collectstatic',
    'flush',
    'loaddata',
    'createsuperuser',
    'runserver',
    'shell',
    'dbshell',
}
IS_TESTING = _MANAGEMENT_COMMAND == 'test'
_ARGV_TEXT = ' '.join(sys.argv).lower()
IS_STATIC_ANALYSIS = 'mypy' in _ARGV_TEXT or 'dmypy' in _ARGV_TEXT
IS_SAFE_MANAGEMENT_CONTEXT = _MANAGEMENT_COMMAND in _SAFE_MANAGEMENT_COMMANDS
IS_SAFE_LOCAL_CONTEXT = IS_TESTING or IS_STATIC_ANALYSIS or IS_SAFE_MANAGEMENT_CONTEXT

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _get_bool('DEBUG', IS_SAFE_LOCAL_CONTEXT)

ALLOWED_HOSTS = _get_list(
    'ALLOWED_HOSTS',
    'localhost;127.0.0.1;[::1]' if DEBUG else ''
)
if not DEBUG and not ALLOWED_HOSTS:
    raise ImproperlyConfigured('ALLOWED_HOSTS must be configured when DEBUG is disabled')

INTERNAL_IPS = ['127.0.0.1'] if DEBUG else []

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = _get_secret('SECRET_KEY', '')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'local-dev-secret-key-not-for-production'
    else:
        raise ImproperlyConfigured('SECRET_KEY must be configured when DEBUG is disabled')

# MAIL SETUP
EMAIL_HOST = _get_secret('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '1025'))
EMAIL_USE_SSL = os.environ.get('EMAIL_SSL', False) in _TRUE_VARIANTS
EMAIL_USE_TLS = os.environ.get('EMAIL_TLS', False) in _TRUE_VARIANTS
EMAIL_HOST_USER = _get_secret('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = _get_secret('EMAIL_HOST_PASSWORD', '')

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
SERVER_EMAIL = EMAIL_HOST_USER
EMAIL_ADMIN = EMAIL_HOST_USER
EMAIL_BACKEND = \
    'django.core.mail.backends.smtp.EmailBackend' \
    if EMAIL_HOST != '' else \
    'django.core.mail.backends.console.EmailBackend'


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'django_filters',
    'rest_framework',
    'django_rest_passwordreset',
    'corsheaders',

    'apps.users',
    'apps.library',
    'apps.rsform',
    'apps.oss',
    'apps.rsmodel',
    'apps.prompt',

    'drf_spectacular',
    'drf_spectacular_sidecar',
]
if DEBUG:
    INSTALLED_APPS.append('django_extensions')


REST_FRAMEWORK = {
    'TEST_REQUEST_DEFAULT_FORMAT': 'json',
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny'
        if DEBUG else
        'rest_framework.permissions.IsAuthenticated'
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'login': '5/minute',
        'signup': '3/hour',
        'password_reset': '5/hour',
    }
}


CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = _get_list('CORS_ALLOWED_ORIGINS', 'http://localhost:3000')
CSRF_TRUSTED_ORIGINS = _get_list('CSRF_TRUSTED_ORIGINS', 'http://localhost:3000')
CSRF_COOKIE_AGE = 365 * 24 * 60 * 60
SESSION_COOKIE_AGE = 365 * 24 * 60 * 60 * 2
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'same-origin'
SECURE_HSTS_SECONDS = 3600 if not DEBUG else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG

_domain = os.environ.get('CSRF_COOKIE_DOMAIN', '')
if _domain != '':
    CSRF_COOKIE_DOMAIN = _domain
    SESSION_COOKIE_DOMAIN = _domain


MIDDLEWARE = [
    'django.middleware.gzip.GZipMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'
LOGIN_URL = '/admin/login'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
APPEND_SLASH = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/
STATIC_ROOT = os.environ.get('STATIC_ROOT', os.path.join(BASE_DIR, 'static'))
STATIC_URL = 'static/'
MEDIA_ROOT = os.environ.get('MEDIA_ROOT', os.path.join(BASE_DIR, 'media'))
MEDIA_URL = 'media/'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [str(BASE_DIR) + '/templates/'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': os.environ.get('DB_ENGINE', 'django.db.backends.sqlite3'),
        'NAME': os.environ.get('DB_NAME', BASE_DIR / 'db.sqlite3'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': _get_secret('DB_PASSWORD', ''),
        'HOST': os.environ.get('DB_HOST'),
        'DB_PORT': os.environ.get('DB_PORT'),
    }
}

# drf-spectacular settings. API docs generator
# https://drf-spectacular.readthedocs.io/en/latest/settings.html
SPECTACULAR_SETTINGS = {
    'TITLE': 'ConceptPortal API',
    'DESCRIPTION': 'Портал для работы с экспликациями концептуальных схем',
    'VERSION': '0.1.2',
    'SERVE_INCLUDE_SCHEMA': False,

    'COMPONENT_SPLIT_PATCH': True,
    'COMPONENT_SPLIT_REQUEST': True,

    'SERVE_PERMISSIONS': ['rest_framework.permissions.AllowAny'],
    'SERVE_AUTHENTICATION': None,

    'DISABLE_ERRORS_AND_WARNINGS': False,

    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'tryItOutEnabled': False,
        'supportedSubmitMethods': [''],
    },
    'SWAGGER_UI_DIST': 'SIDECAR',
    'SWAGGER_UI_FAVICON_HREF': 'SIDECAR',
    'REDOC_DIST': 'SIDECAR'
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS: list[dict[str, str]] = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'ru'
TIME_ZONE = 'Europe/Moscow'
USE_I18N = True
USE_TZ = True


# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Graph model settings for visualization
# https://django-extensions.readthedocs.io/en/latest/graph_models.html
GRAPH_MODELS = {
    'all_applications': True,
    'group_models': True,
}


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO')
    }
}

if len(sys.argv) > 1 and sys.argv[1] == 'test':
    logging.disable(logging.CRITICAL)
