# Generated by Django 6.0.1 on 2026-02-09 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0008_alter_libraryitem_item_type'),
        ('rsform', '0006_attribution_delete_association'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstituentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Данные')),
                ('constituent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsmodel_bindings', to='rsform.constituenta', verbose_name='Конституента')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsmodel_constituents', to='library.libraryitem', verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Конституента модели',
                'verbose_name_plural': 'Конституенты модели',
            },
        ),
        migrations.CreateModel(
            name='RSModel',
            fields=[
                ('model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='rsmodel_data', serialize=False, to='library.libraryitem', verbose_name='Модель')),
                ('schema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rsmodels', to='library.libraryitem', verbose_name='Концептуальная схема')),
            ],
            options={
                'verbose_name': 'Концептуальная модель',
                'verbose_name_plural': 'Концептуальные модели',
            },
        ),
    ]
