# Generated by Django 6.0.1 on 2026-02-12 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0008_alter_libraryitem_item_type'),
        ('rsmodel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsmodel',
            name='model',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='rsmodels', serialize=False, to='library.libraryitem', verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='rsmodel',
            name='schema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_schema', to='library.libraryitem', verbose_name='Концептуальная схема'),
        ),
    ]
