# Generated by Django 6.0.1 on 2026-02-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsmodel', '0002_alter_rsmodel_model_alter_rsmodel_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='constituentdata',
            name='type',
            field=models.TextField(default=123, verbose_name='Тип данных'),
            preserve_default=False,
        ),
    ]
