import { defineConfig } from 'tsup';

const entryFiles = [
  'src/index.ts',
  'src/rslang/index.ts',
  'src/rslang/api.ts',
  'src/rslang/error.ts',
  'src/rslang/labels.ts',
  'src/rslang/ast-annotations.ts',
  'src/rslang/typification-graph.ts',
  'src/rslang/eval/value.ts',
  'src/rslang/eval/value-api.ts',
  'src/rslang/eval/evaluator.ts',
  'src/rslang/eval/evaluation-cache.ts',
  'src/rslang/eval/calculator.ts',
  'src/rslang/parser/parser.ts',
  'src/rslang/parser/normalize.ts',
  'src/rslang/parser/syntax-errors.ts',
  'src/rslang/parser/expression-generator.ts',
  'src/rslang/parser/token.ts',
  'src/rslang/parser/parser.terms.ts',
  'src/rslang/semantic/analyzer.ts',
  'src/rslang/semantic/arguments-extractor.ts',
  'src/rslang/semantic/type-auditor.ts',
  'src/rslang/semantic/typification.ts',
  'src/rslang/semantic/typification-api.ts',
  'src/rslang/semantic/typification-parser.ts',
  'src/rslang/semantic/value-auditor.ts',
  'src/rslang/semantic/value-class.ts',
  'src/library/index.ts',
  'src/library/library.ts',
  'src/library/library-api.ts',
  'src/library/folder-tree.ts',
  'src/library/rsform.ts',
  'src/library/rsform-api.ts',
  'src/library/rsmodel.ts',
  'src/library/rsmodel-api.ts',
  'src/library/rsengine.ts',
  'src/library/structure-planner.ts',
  'src/library/oss.ts',
  'src/library/oss-api.ts',
  'src/library/oss-layout.ts',
  'src/library/oss-layout-api.ts',
  'src/graph/index.ts',
  'src/graph/graph.ts',
  'src/parsing/index.ts',
  'src/parsing/ast.ts',
  'src/parsing/lezer-tree.ts',
  'src/cctext/index.ts',
  'src/cctext/language.ts',
  'src/cctext/language-api.ts',
  'src/shared/index.ts',
  'src/shared/branded.ts',
  'src/shared/hash.ts'
];

export default defineConfig({
  entry: entryFiles,
  format: ['esm'],
  dts: true,
  sourcemap: true,
  clean: true,
  splitting: false,
  treeshake: false,
  target: 'es2022',
  outDir: 'dist'
});
