# Generated by Django 6.0.4 on 2026-07-29 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='Название')),
                ('prefix', models.CharField(db_index=True, max_length=16, verbose_name='Префикс')),
                ('key_hash', models.CharField(max_length=64, unique=True, verbose_name='Хэш ключа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Последнее использование')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Отозван')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'API-ключ',
                'verbose_name_plural': 'API-ключи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_label', models.CharField(blank=True, default='', max_length=100, verbose_name='Название ключа')),
                ('key_prefix', models.CharField(blank=True, default='', max_length=16, verbose_name='Префикс ключа')),
                ('action', models.CharField(db_index=True, max_length=64, verbose_name='Действие')),
                ('item_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='ID объекта')),
                ('item_alias', models.CharField(blank=True, default='', max_length=64, verbose_name='Шифр объекта')),
                ('item_title', models.CharField(blank=True, default='', max_length=255, verbose_name='Название объекта')),
                ('status_code', models.PositiveSmallIntegerField(default=200, verbose_name='HTTP-статус')),
                ('summary', models.CharField(blank=True, default='', max_length=500, verbose_name='Кратко')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_action_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('api_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to='agents.apikey', verbose_name='API-ключ')),
            ],
            options={
                'verbose_name': 'Журнал действий агента',
                'verbose_name_plural': 'Журнал действий агентов',
                'ordering': ['-created_at'],
            },
        ),
    ]
