# Generated by hand for the unreleased agents app.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRateState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_window_started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало окна чтения')),
                ('read_count', models.PositiveIntegerField(default=0, verbose_name='Чтений в окне')),
                ('write_window_started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало окна правок')),
                ('write_count', models.PositiveIntegerField(default=0, verbose_name='Правок в минуту')),
                ('write_hour_started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало часового окна правок')),
                ('write_hour_count', models.PositiveIntegerField(default=0, verbose_name='Правок в час')),
                ('heavy_hour_started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало окна тяжёлых правок')),
                ('heavy_hour_count', models.PositiveIntegerField(default=0, verbose_name='Тяжёлых правок в час')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_rate_state', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лимит вызовов агента',
                'verbose_name_plural': 'Лимиты вызовов агентов',
            },
        ),
    ]
