# Generated by hand for the unreleased agents app.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agentratestate'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentactionlog',
            name='request_text',
            field=models.TextField(blank=True, default='', verbose_name='Текст запроса'),
        ),
        migrations.CreateModel(
            name='AgentLogCleanup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя очистка')),
            ],
            options={
                'verbose_name': 'Очистка журнала агентов',
                'verbose_name_plural': 'Очистка журнала агентов',
            },
        ),
    ]
