# Generated by Django 6.1.1 on 2026-10-02 10:55

from django.db import migrations, models
from django.utils import timezone


def revoke_legacy_sha256_keys(apps, schema_editor):
    ''' Invalidate pre-password-hasher SHA-256 digests (64 hex chars, no ``$``).

    Plaintext is unavailable, so those rows cannot be rehashed. Owners must
    mint new keys after deploy.
    '''
    ApiKey = apps.get_model('agents', 'ApiKey')
    now = timezone.now()
    for key in ApiKey.objects.filter(revoked_at__isnull=True).iterator():
        digest = key.key_hash or ''
        if '$' not in digest and len(digest) == 64:
            key.revoked_at = now
            key.save(update_fields=['revoked_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_agentlog_request_and_cleanup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='key_hash',
            field=models.CharField(max_length=128, unique=True, verbose_name='Хэш ключа'),
        ),
        migrations.RunPython(revoke_legacy_sha256_keys, migrations.RunPython.noop),
    ]
