// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Expression = 1,
  TextFunction = 2,
  ComplexIndex = 3,
  ConstructPrefix = 4,
  Integer = 5,
  Global = 6,
  Radical = 7,
  Local = 8,
  Index = 9
