// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Expression = 1,
  Local = 2,
  Index = 3,
  Literal = 5,
  Global = 6,
  Radical = 7,
  Filter = 20,
  ComplexIndex = 21,
  PrefixD = 26,
  PrefixI = 27,
  PrefixR = 29,
  Function = 31,
  TextFunction = 32,
  Predicate = 45
