// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Expression = 1,
  Literal = 2,
  Local = 3,
  Index = 4,
  Global = 5,
  Radical = 6,
  Filter = 20,
  ComplexIndex = 21,
  PrefixD = 26,
  PrefixI = 27,
  PrefixR = 31,
  Function = 32,
  TextFunction = 33,
  Predicate = 45
