# Generated by Django 5.0.7 on 2024-07-25 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oss', '0001_initial'),
        ('rsform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inheritance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_child', to='rsform.constituenta', verbose_name='Наследованная конституента')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_parent', to='rsform.constituenta', verbose_name='Исходная конституента')),
            ],
            options={
                'verbose_name': 'Наследование синтеза',
                'verbose_name_plural': 'Отношение наследования конституент',
                'unique_together': {('parent', 'child')},
            },
        ),
    ]
