# Generated by Django 5.0.7 on 2024-07-22 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oss', '0001_initial'),
        ('rsform', '0008_alter_libraryitem_item_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationSchema',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('rsform.libraryitem',),
        ),
        migrations.AlterField(
            model_name='operation',
            name='oss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='oss.operationschema', verbose_name='Схема синтеза'),
        ),
    ]
