# Generated by Django 5.0.7 on 2024-07-30 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oss', '0002_inheritance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='sync_text',
        ),
    ]
