# Generated by Django 5.0.7 on 2024-08-02 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oss', '0004_remove_substitution_transfer_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='inheritance',
            name='operation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='inheritances', to='oss.operation', verbose_name='Операция'),
            preserve_default=False,
        ),
    ]
