# Generated by Django 5.1.7 on 2025-03-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oss', '0008_alter_operation_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
