# Generated by Django 5.1.7 on 2025-03-25 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oss', '0009_alter_operation_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='comment',
            new_name='description',
        ),
    ]
