# Generated by Django 5.2.1 on 2025-06-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oss', '0012 restructure_layout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layout',
            name='data',
            field=models.JSONField(default=list, verbose_name='Расположение'),
        ),
    ]
