name: Backend CI

defaults:
  run:
    working-directory: rsconcept/backend

on:
  push:
    branches: [ "main" ]
    paths:
      - rsconcept/backend/**
      - .github/workflows/backend.yml
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_dev.txt
    - name: Lint
      run: |
        pylint cctext
        mypy cctext
    - name: Run Tests
      run: |
        python manage.py check
        python manage.py test
