# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Frontend CI

defaults:
  run:
    working-directory: rsconcept/frontend

on:
  push:
    branches: ["main"]
    paths:
      - rsconcept/frontend/**
      - .github/workflows/frontend.yml
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache-dependency-path: rsconcept/frontend/package-lock.json
          cache: "npm"
      - name: Build
        run: |
          npm install -g typescript vite jest playwright
          npm ci
          npx playwright install --with-deps
          npm run build --if-present
      - name: Run CI
        run: |
          npm run lint
          npm test
          npm run test:e2e
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
  notify-failure:
    runs-on: ubuntu-latest
    needs: build
    if: failure()
    defaults:
      run:
        working-directory: .
    steps:
      - name: Send Telegram Notification
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="❌ Front build failed! Repository: ${{ github.repository }} Commit: ${{ github.sha }}"
