# Generated by Django 5.0.7 on 2024-07-25 16:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constituenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=-1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Позиция')),
                ('alias', models.CharField(default='undefined', max_length=8, verbose_name='Имя')),
                ('cst_type', models.CharField(choices=[('basic', 'Base'), ('constant', 'Constant'), ('structure', 'Structured'), ('axiom', 'Axiom'), ('term', 'Term'), ('function', 'Function'), ('predicate', 'Predicate'), ('theorem', 'Theorem')], default='basic', max_length=10, verbose_name='Тип')),
                ('convention', models.TextField(blank=True, default='', verbose_name='Комментарий/Конвенция')),
                ('term_raw', models.TextField(blank=True, default='', verbose_name='Термин (с отсылками)')),
                ('term_resolved', models.TextField(blank=True, default='', verbose_name='Термин')),
                ('term_forms', models.JSONField(default=list, verbose_name='Словоформы')),
                ('definition_formal', models.TextField(blank=True, default='', verbose_name='Родоструктурное определение')),
                ('definition_raw', models.TextField(blank=True, default='', verbose_name='Текстовое определение (с отсылками)')),
                ('definition_resolved', models.TextField(blank=True, default='', verbose_name='Текстовое определение')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library.libraryitem', verbose_name='Концептуальная схема')),
            ],
            options={
                'verbose_name': 'Конституента',
                'verbose_name_plural': 'Конституенты',
            },
        ),
    ]
