# Generated by Django 5.1 on 2024-09-04 09:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constituenta',
            name='order',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Позиция'),
        ),
    ]
