# Generated by Django 4.2.7 on 2023-12-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsform', '0002_librarytemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constituenta',
            name='definition_raw',
            field=models.TextField(blank=True, default='', verbose_name='Текстовое определение (с отсылками)'),
        ),
        migrations.AlterField(
            model_name='constituenta',
            name='definition_resolved',
            field=models.TextField(blank=True, default='', verbose_name='Текстовое определение'),
        ),
    ]
