# Generated by Django 5.2.4 on 2025-07-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsform', '0003_alter_constituenta_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='constituenta',
            name='crucial',
            field=models.BooleanField(default=False, verbose_name='Ключевая'),
        ),
    ]
