# Generated by Django 4.2.10 on 2024-03-03 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rsform', '0003_alter_constituenta_definition_raw_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, verbose_name='Версия')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('data', models.JSONField(verbose_name='Содержание')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rsform.libraryitem', verbose_name='Схема')),
            ],
            options={
                'verbose_name': 'Версии',
                'verbose_name_plural': 'Версия',
                'unique_together': {('item', 'version')},
            },
        ),
    ]
