# Generated by Django 5.0.6 on 2024-05-20 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsform', '0004_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.AlterModelOptions(
            name='version',
            options={'verbose_name': 'Версия', 'verbose_name_plural': 'Версии'},
        ),
    ]
