# Generated by Django 5.2.4 on 2025-08-21 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsform', '0005_alter_constituenta_cst_type_association'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_attribute', to='rsform.constituenta', verbose_name='Атрибутирующая конституента')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_container', to='rsform.constituenta', verbose_name='Составная конституента')),
            ],
            options={
                'verbose_name': 'Атрибутирование конституент',
                'verbose_name_plural': 'Атрибутирования конституент',
                'unique_together': {('container', 'attribute')},
            },
        ),
        migrations.DeleteModel(
            name='Association',
        ),
    ]
