# Generated by Django 5.0.7 on 2024-07-22 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsform', '0008_alter_libraryitem_item_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSForm',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('rsform.libraryitem',),
        ),
        migrations.AlterField(
            model_name='constituenta',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rsform.rsform', verbose_name='Концептуальная схема'),
        ),
        migrations.AlterField(
            model_name='librarytemplate',
            name='lib_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rsform.rsform', verbose_name='Источник'),
        ),
    ]
